### PR TITLE
Implement xml:base

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
Any opinion on these commits?

**Comment by Chris00** [comment]
@dsheets any opinion on the way `xml:base` is handled here?

**Comment by Chris00** [comment]
>  I don't see where [...] the propagation of xml:base happens 
The function `generate_catcher` takes lists of callbacks, each with an `xmlbase: Uri.t option` argument, to parse sub-nodes (and attributes).  `generate_catcher` makes sure the `xml:base` it receives is given (appropriately modified) to callbacks.

**Comment by Chris00** [comment]
I now [get xmlbase](https://github.com/Cumulus/Syndic/pull/52/files#diff-869feebcb9446d6f6c16f8f56cb5e77eL42) before parsing the other attributes and sub-elements.

**Comment by Chris00** [comment]
@dsheets Thanks a lot for your careful reading of my changes!

**Comment by Chris00** [comment]
@dinosaure I intend to merge it later today unless you comment.

**Comment by dinosaure** [comment]
Sorry for my no response but I have big problem with my only computer (in China) for a long time. I saw a piece of PR and I trust you. Sorry.

**Comment by Chris00** [comment]
Sorry for you.  I also fixed the `<content:encoded>` which is required for the OCaml web site.  How about to cut a new release?

**Pull request merged**
