### PR TITLE
Test suite

### PR DESCRIPTION
**Pull request by dinosaure**
I think it's good for a start. The code is not super readable but it did its job. If you have any comments @Chris00, do not hesitate. I use the API W3C whether Syndic reason to reject a document or we have a problem of implementation.

For now, there is only one test with [OCaml](http://ocaml.org/feed.xml). But you can complete (I do not have a big base of flow).

### CODE REVIEW

**Comment by dinosaure** [comment]
And the [OCaml](http://ocaml.org/feed.xml) is [not valid](http://validator.w3.org/feed/check.cgi?url=http://ocaml.org/feed.xml) :confused:.

**Comment by Chris00** [comment]
I did not have time to read it in details yet but I like the idea.

We may want that decisions like the [Atom.link title](https://github.com/Cumulus/Syndic/issues/55#issuecomment-92781971) one come together with a corresponding W3C test.

**Comment by Chris00** [comment]
> And the OCaml is not valid

The remaining problem is the [URN scheme not being supported](https://github.com/mirage/ocaml-uri/issues/67) by Uri.  (Other problems are fixed I think — but I have not yet updated Syndic on the server but the commits > version 1.3 aim to fix the W3C reported issues).  This should be fixed in Uri 1.9 and I intend to make Syndic require it once it will be released.

**Comment by Chris00** [comment]
I checked the code and made a few modifications that I will push soon.  There is something that still puzzles me: if I understand the intention, the `test` program is supposed to use the W3C validator to check that when the library reject some feed, so does the validator.  However, the `result` of `make_test (src, fmt, result)` is not used at all...

**Pull request merged**
